### ISSUE TITLE
enable reset generate config on fly

### ISSUE THREAD

**Issue by depenglee1707** [OpenCSGs/llm-inference#104]
for now the `generation` params is addressed in yaml files,
add the ability reset these params on fly is useful:
```
    generate_kwargs:
      do_sample: false
      max_new_tokens: 512
      min_new_tokens: 16
      temperature: 0.7
      repetition_penalty: 1.1
      top_p: 0.8
      top_k: 50
      pad_token: "<|extra_0|>"
      eos_token: "<|endoftext|>"
```
