### ISSUE TITLE
vllm implements cannot support download model from repo besides hg

### ISSUE THREAD

**Issue by depenglee1707** [OpenCSGs/llm-inference#120]
```
  initialization:
    runtime_env:
      env_vars:
        HF_ENDPOINT: https://hub.opencsg.com/hf
    initializer:
      type: Vllm
      from_pretrained_kwargs:
        trust_remote_code: true
    pipeline: vllm
```
this cannot work as expected
