### ISSUE TITLE
Set default model download address

### ISSUE THREAD

**Issue by SeanHH86** [OpenCSGs/llm-inference#15]
Update default model download address to opencsg

**Comment by SeanHH86** [comment]
Model fold structure downloaded by the following config  is different from `huggingface.co`.  

```
  initialization:
    runtime_env:
      env_vars:
        HF_ENDPOINT: https://hub.opencsg.com/hf
```
